name: CI/CD Pipeline Frontend

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas unitarias
        run: npm run test
      - name: Compilar Frontend
        run: npm run build
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pintoduoc/fullstack3-frontend:latest
